apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zb6aj2bd1-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-4a5252dac9.qcb2.p3.openshiftapps.com/rhtap/rhtap-qe:f1a68955fbb5131e3c3c497b6de8e8febef1e086@sha256:0a1f8a63ee46f11fc5cd323673bc959bc041f99d978c437153490c18e8d7ffca
          name: container-image
